### ISSUE TITLE
Review new student topics view for current topics

### ISSUE THREAD

**Issue by arlee-shelby** [arlee-shelby/reimplementation-front-end#14]
I added a new view/implementation for this on the feature-filterByYourTopics branch, which should be reviewed by everyone so we can decide which one we want to keep.

**Comment by AryanT7** [comment]
Checked the "Topics Feature Edit" in "Topics (Admin View)". Everything is working well and looks good. I was wondering if we require the "Allow reviewer to choose which topic to review?" choice since reviewers are randomly designated.

**Comment by arlee-shelby** [comment]
I believe this was added because it is currently an option on the previous implementation for Sign up topics

**Comment by KomachiZ** [comment]
I ran this branch, and the UI display of the current branch is more make sense
